//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiFaceRec {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class MainSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MainSettings defaultInstance = ((MainSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MainSettings())));
        
        public static MainSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\YandexDisk\\Документы\\univer\\биометрика\\лабораторная\\Face")]
        public string sourceDbPath {
            get {
                return ((string)(this["sourceDbPath"]));
            }
            set {
                this["sourceDbPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\YandexDisk\\Документы\\univer\\биометрика\\лабораторная\\FaceSplit\\FormattedDb")]
        public string formattedDbPath {
            get {
                return ((string)(this["formattedDbPath"]));
            }
            set {
                this["formattedDbPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\YandexDisk\\Документы\\univer\\биометрика\\лабораторная\\FaceSplit\\TestDb")]
        public string testDbPath {
            get {
                return ((string)(this["testDbPath"]));
            }
            set {
                this["testDbPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TrainedLabels.txt")]
        public string trainedLabelsFileName {
            get {
                return ((string)(this["trainedLabelsFileName"]));
            }
            set {
                this["trainedLabelsFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public float maxLastDistance {
            get {
                return ((float)(this["maxLastDistance"]));
            }
            set {
                this["maxLastDistance"] = value;
            }
        }
    }
}
